name: standard
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  build_runner: ^2.3.3
  either_dart: ^0.4.0
  ferry: ^0.14.2+1
  ferry_flutter: ^0.8.1
  ferry_generator: ^0.8.1
  ferry_hive_store: ^0.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  gql_http_link: ^1.0.1
  gql_link: ^1.0.0
  hive: ^2.2.3
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  intl: ^0.17.0
  loggy: ^2.0.3
  path_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
